set(_CATKIN_CURRENT_PACKAGE "nox")
set(nox_VERSION "1.0.0")
set(nox_MAINTAINER "Robin Baran <r-baran@hotmail.fr>")
set(nox_PACKAGE_FORMAT "2")
set(nox_BUILD_DEPENDS "nox_description" "roscpp" "rospy" "teb_local_planner")
set(nox_BUILD_EXPORT_DEPENDS "nox_description" "roscpp" "rospy" "teb_local_planner")
set(nox_BUILDTOOL_DEPENDS "catkin")
set(nox_BUILDTOOL_EXPORT_DEPENDS )
set(nox_EXEC_DEPENDS "nox_description" "roscpp" "rospy" "teb_local_planner")
set(nox_RUN_DEPENDS "nox_description" "roscpp" "rospy" "teb_local_planner")
set(nox_TEST_DEPENDS )
set(nox_DOC_DEPENDS )
set(nox_URL_WEBSITE "http://wiki.ros.org/Robots/Nox")
set(nox_URL_BUGTRACKER "")
set(nox_URL_REPOSITORY "")
set(nox_DEPRECATED "")